### ISSUE TITLE
Configure CC-URL and Restart

### ISSUE THREAD

**Issue by mike2246** [Bendr0id/xmrigCC-amd#10]
I can CPU version of XMRig working perfectly, however I cannot get the AMD version to connect to any server that I setup I get the following error
      Configure CC-URL and Restart    CC Feature is now deactivated

**Comment by mike2246** [comment]
I just tried a straight batch file and it works but I cannot change the config file through the dashboard.  Does someone have a working AMD Config file to share that I can test?

**Comment by Bendr0id** [comment]
Just make sure the config file is in the same folder where you execute the miner(which could be different to the .exe location) . Just use the one which is in the binary package/release. That works.

If needed you can add thr parameter -c path/to/the/config.json

Update is definitely working in this case.

**Comment by mike2246** [comment]
Here's my Config file (same folder as Miner)

{
    "algo": "cryptonight",
    "api": {
        "port": 0,
        "access-token": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "background": false,
    "cache": true,
    "colors": true,
    "donate-level": 1,
    "log-file": null,
    "opencl-platform": 0,
    "opencl-loader": "OpenCL.dll",
    "pools": [
        {
            "url": "pool.minexmr.com:7777",
            "user": "MyWallet",
            "pass": "x",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "variant": 1
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "threads": [
        {
            "index": 0,
            "intensity": 896,
            "worksize": 8,
            "strided_index": 1,
            "mem_chunk": 2,
            "comp_mode": true,
            "affine_to_cpu": false
        }
    ],
    "user-agent": null,
    "syslog": false,
    "watch": false,
    "cc-client": {
        "url": "http://MyIPAddress:3344",
        "access-token": "mySecret",
        "worker-id": null,
        "update-interval-s": 10,
        "use-tls": false
    }
}

**Comment by Bendr0id** [comment]
First of all. That will never work: "url": "http://MyIPAddress:3344",
it has to be: "url": "MyIPAddress:3344", no http in front.

Config looks ok so far. How do you start the binary, just click the exe? Batchfile isn't needed at all.

**Comment by mike2246** [comment]
got it, thanks!
