### ISSUE TITLE
xmrig-amd 1.7.0 release for monero fork

### ISSUE THREAD

**Issue by ese105** [Bendr0id/xmrigCC-amd#11]
is this release for monero fork?

**Comment by yangsystem** [comment]
it will come today or tomorrow. It is in testing now and it is working.

**Comment by ese105** [comment]
tq ;)

**Comment by Bendr0id** [comment]
Do you build on your own?
Its merged to master

**Comment by Bendr0id** [comment]
https://github.com/Bendr0id/xmrigCC-amd/releases
