### ISSUE TITLE
Can't get the AMD version to mine Monero with CNv2, it is always using CNv1

### ISSUE THREAD

**Issue by kensagle** [Bendr0id/xmrigCC-amd#14]
It is probably a config error on my side.  Is there a sample config.json or a wiki on the config file options?

I tried 

"pow-variant" : "2",

and

"pow-variant" : "auto",

**Comment by djfinch** [comment]
It is just "variant"...
https://github.com/Bendr0id/xmrigCC-amd/blob/master/src/config.json#L26

**Comment by Bendr0id** [comment]
Oh yeah sorry. The Wiki page counts for CPU miner only. Need to upgrade the wiki page for GPU. It has slightly different params.

**Comment by kensagle** [comment]
That worked!  Thanks for the super fast reply.  Closing.
