### ISSUE TITLE
Does this version of 1.6.5 support bittube

### ISSUE THREAD

**Issue by demaxiya1982** [Bendr0id/xmrigCC-amd#2]
1.6.5的这个版本支持 bittube 吗
我看源代码,Algorithm.cpp
 没有这个选项
CPU版本好用 但是我是AMD  VEGA显卡的

**Comment by demaxiya1982** [comment]
Does this version of 1.6.5 support bittube

I look at the source code, Algorithm.cpp

No this option

The CPU version is good, but I'm the AMD VEGA graphics card

**Comment by Bendr0id** [comment]
Upcoming release 1.6.6 will do. Will be released today or tomorrow.

Am 22.07.2018 03:29 schrieb demaxiya1982 <notifications@github.com>:

Does this version of 1.6.5 support bittube

I look at the source code, Algorithm.cpp

No this option

The CPU version is good, but I'm the AMD VEGA graphics card

**Comment by demaxiya1982** [comment]
Thank you very much! The tool you made is very good!

**Comment by Bendr0id** [comment]
Latest master contains support for cn-heavy/tube

**Comment by Bendr0id** [comment]
Released in 1.6.5_beta3
