### ISSUE TITLE
Latest version broke xmrig api

### ISSUE THREAD

**Issue by unsivilaudio** [Bendr0id/xmrigCC-amd#20]
Either you removed it, or it no longer is working.  I have an xmrig-amd api port defined I'm using a scripts for gathering information, the port is no longer being made active after updating to the latest version; no other changes to the system.

**Comment by Bendr0id** [comment]
Possible that I missed the build flag... Didn't heard that from other users yet, but can be.

Which os?

**Comment by Bendr0id** [comment]
Windows or Linux?

**Comment by unsivilaudio** [comment]
Linux.

**Comment by Bendr0id** [comment]
Oh yeah that can be.. I'll rebuild it.

**Comment by Bendr0id** [comment]
Can you test again?

https://github.com/Bendr0id/xmrigCC-amd/releases/download/1.8.6/xmrigCC-amd-1.8.6-with_tls-gcc7-linux-static-miner_only-x64.tar.gz

**Comment by unsivilaudio** [comment]
Yay, it works again, what build flags did you use?

**Comment by Bendr0id** [comment]
Accidentally compiled with -DWITH_HTTPD=OFF

**Comment by unsivilaudio** [comment]
Thanks for looking into that. :)
