### ISSUE TITLE
Version call results in infinite console spam [1.8.6+]

### ISSUE THREAD

**Issue by unsivilaudio** [Bendr0id/xmrigCC-amd#21]
Just a heads up. I tested both your release and my own build display this behavior.

http://prntscr.com/m1c8sb

You have to close the session and kill the process in a new session to get it to stop.

**Comment by Bendr0id** [comment]
Sorry, but this printout doesnt exist in xmrigCC-amd.

**Comment by unsivilaudio** [comment]
Yeah check again.....sorry I linked the wrong screenshot the first time.

**Comment by Bendr0id** [comment]
Do you tested my release? Can't see any error, looks like a mem corruption.

**Comment by unsivilaudio** [comment]
Yeah I downloaded the latest release.  This doesn't effect the base xmrigCC either.  It's only present in the AMD fork.

**Comment by unsivilaudio** [comment]
I should probably clarify, the miner works fine.  The version call function just ends up with spam.

**Comment by Bendr0id** [comment]
Which version call?

**Comment by unsivilaudio** [comment]
xmrigDaemon-amd --version

**Comment by Bendr0id** [comment]
Same for --help i bet. I'll check that.

**Comment by Bendr0id** [comment]
Fixed in Master

**Comment by unsivilaudio** [comment]
Great, thanks again.
