### ISSUE TITLE
Fork coming today

### ISSUE THREAD

**Issue by distributorofpain** [Bendr0id/xmrigCC-amd#27]
Are you able to merge in the latest xmrig-amd?  There are fixes and stuff needed in prep for the fork.

**Comment by Bendr0id** [comment]
There is nothin to be merged. The latest changes from upstream are only some network fixes. There is nothing RandomX related.

XMRig did all the randomX stuff on his all-in-one miner. 

XMRigCC will be based on the new all-in-one miner soon too.
