### ISSUE TITLE
The reboot program will fail

### ISSUE THREAD

**Issue by demaxiya1982** [Bendr0id/xmrigCC-amd#5]
XmrigCC-amd remotely restarts at work. There will be time to die. No initialization procedure has been reinitialized.

I come to China and I can't speak English. If I use Baidu translate, if it is not accurate enough, please forgive me.

**Comment by Bendr0id** [comment]
Sorry i dont unterstand

**Comment by Bendr0id** [comment]
Please try this version:

https://github.com/Bendr0id/xmrigCC-amd/releases/tag/1.6.5_beta4
