### ISSUE TITLE
OpenCL Loader is not working on OSX

### ISSUE THREAD

**Issue by djfinch** [Bendr0id/xmrigCC-amd#7]
Hi Ben,

This issue, https://github.com/xmrig/xmrig-amd/issues/155.

xmrig removed `#ifdef __APPLE__` conditions so compiler is trying to include Khronos OpenCL instead of Apple's built-in ones and they seems to be incompatible there. I'm somehow able to fix sourcecode to reuse Apple's OpenCL again but i'm not able to create dynamic lib to use with xmrig from them (.dylib like .dll/.so). Funny workaround is using amd backend dylib created by xmrstak, but... Any idea?

**Comment by Bendr0id** [comment]
Hi @djfinch,

It's hard for me to debug without a Mac..

When you have a solution, please let me know. Every help is appreciated.

**Comment by mrlando** [comment]
I have 0 coding skills but I do have a Mac, so if it's any help to you I can send you build/error logs...

**Comment by djfinch** [comment]
Hi Ben,

Sorry, I'm busy :) Untested but on-mac-working fix is https://github.com/xmrig/xmrig-amd/pull/158 here but I don't have any non-mac miner (with AMD or any general OCL capable GPU) to test with so let's wait. :) Thanks!

**Comment by djfinch** [comment]
Hi Ben,

JFYI : I can confirm that this is fixed in https://github.com/xmrig/xmrig-amd/commit/7d35a61133e8ac797642bf27ca62712f5380c63c and autoconfig in https://github.com/xmrig/xmrig-amd/commit/250dddb29662b41144019b058af333c69ad907af. Can you please include this fix in future release? Thank you.

Kind regards,
Finch

**Comment by Bendr0id** [comment]
@djfinch can you please try the latest master..?

**Comment by djfinch** [comment]
@Bendr0id  Thanks!
It's OK after https://github.com/Bendr0id/xmrigCC-amd/pull/9.
